### ISSUE TITLE
Developer Tools option should be removed

### ISSUE THREAD

**Issue by sitemapxml** [antonreshetov/massCode#120]
![screenshot 2020-07-13](https://user-images.githubusercontent.com/33502827/87353161-91ae3e00-c55c-11ea-889d-96c0bef88031.jpg)

There is no sense of putting "Developer Tools" option inside desktop app. I think it should be removed and keyboard shortcut should be also disabled to avoid accidental activation. 

## To Reproduce
Click `Help -> Open Developer Tools Alt+Ctrl+I`

![screenshot 2020-07-13(1)](https://user-images.githubusercontent.com/33502827/87353462-24e77380-c55d-11ea-9827-b60f122b460d.jpg)

**Comment by antonreshetov** [comment]
It is a common practice to add Dev Tools to applications made on Electron
