### ISSUE TITLE
All snippets disappeared in v2.0.0-beta.1 - How to import snippets from v1.3?

### ISSUE THREAD

**Issue by cacan** [antonreshetov/massCode#140]
## Describe the bug

All snippets disappeared after installing v2.0.0-beta.1

Is there a way to import snippets from the previous version [v1.3]?

## To Reproduce

Install v2.0.0-beta.1 over v1.3

## Expected behavior

v2.0.0-beta.1 imports old snippets

## Environment

Version: v2.0.0-beta.1
OS version and name: Windows 20H2

**Comment by antonreshetov** [comment]
Preferences -> Migrate

**Comment by cacan** [comment]
Thanks, it worked, but got this error message:

![2021_02_17_image-001](https://user-images.githubusercontent.com/406493/108187450-c7c52900-710e-11eb-9f20-f2df1e343501.png)

**Comment by antonreshetov** [comment]
It's weird, I'll have to look into it. Could you try again, while opening devtools to see the messages in the console?

**Comment by snakewa** [comment]
same here

**Comment by antonreshetov** [comment]
@snakewa https://github.com/antonreshetov/massCode/releases/tag/v2.0.0-beta.1
