### ISSUE TITLE
[REQUEST] Search regex syntax or multi-word

### ISSUE THREAD

**Issue by Kianda** [antonreshetov/massCode#143]
I think that the search feature on this kind of software it's really crucial.
It's possible to search multiple words instead of a single pattern?

Example: I have a snippet with the following comment inside:
// add event listeners

If I search for "add listeners" it will never show up.
It's possible to implement a regex syntax to the search box maybe?
Or something like this "add | listeners" to execute a multi-words search.

Thanks!

**Comment by antonreshetov** [comment]
Good suggestion. I'll think about implementing it and including it in v2.
