### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by brekk** [antonreshetov/massCode#17]
Attempting to run massCode 0.5.0 on OSX Mojave 10.14.5, I am immediately greeted with this error:

<img width="447" alt="Screen Shot 2020-01-15 at 07 08 27" src="https://user-images.githubusercontent.com/18919/72409476-2ed31a00-3766-11ea-8dc0-a0c2a5bc1006.png">

**Comment by antonreshetov** [comment]
@brekk please download latest build #13

**Comment by brekk** [comment]
@antonreshetov I must have missed the more recent build. v.0.5.1 works perfectly. Thanks!

**Comment by antonreshetov** [comment]
@brekk just to let you know, the last build is 0.7.1 - https://github.com/antonreshetov/massCode/releases
