### ISSUE TITLE
Bold clone of SnippetLab

### ISSUE THREAD

**Issue by thaikolja** [antonreshetov/massCode#18]
That's a pretty blatant clone of [SnippetLab for Mac](https://www.renfei.org/snippets-lab/), isn't it? Not really the spirit of open source.

**Comment by antonreshetov** [comment]
Well, apart from the external resemblance, there are differences from the stack to such features as the Monaco editor and other differences, right? Or you just wrote this comment without going into detail . And what is the open source spirit in your opinion? It's also not a place for this kind of talk.  There are reddit and other forums. If you have a desire, please create posts there.
