### ISSUE TITLE
massCode doesnt start on Catalina 10.15.2

### ISSUE THREAD

**Issue by pablues** [antonreshetov/massCode#21]
Privet Anton,

just stumbled upon this app and when I'm trying to start it, I get "The application "massCode.app" can't be opened" without further info / instructions. 

I'm on Catalina 10.15.2

Any suggestions?

Paul

**Comment by MichaelSeelisch** [comment]
Had the same problem, solved it by building the application by myself.
Clone the repo, install the dependencies and start the build process.
The generated massCode app in the build folder should work on catalina.

**Comment by antonreshetov** [comment]
Oh, that's weird, because the build goes on the latest version of macOS https://github.com/antonreshetov/massCode/blob/master/.github/workflows/main.yml#L15.

I could use someone's help to fix this problem.

**Comment by dtgay** [comment]
Also having this problem. Was able to run the program by building it myself, as @MichaelSeelisch suggested.

This worked for me:
```bash
git clone https://github.com/antonreshetov/massCode
cd massCode
yarn install
yarn build
```

For what it's worth, the `.app` that built for me is 2 MB larger than the official release, so they are not identical. Not sure how relevant this is.

**Comment by hreyeslo** [comment]
Working on Catalina 10.15.2 -> [Download](https://we.tl/t-s2VFMIBwzZ)

<img width="1024" alt="Captura de pantalla 2020-01-20 a las 17 14 49" src="https://user-images.githubusercontent.com/12648589/72741717-7fa0a380-3ba8-11ea-948c-fe75e889d20d.png">

Code of the master branch and compiled as @MichaelSeelisch suggested.

**Comment by hreyeslo** [comment]
> Oh, that's weird, because the build goes on the latest version of macOS https://github.com/antonreshetov/massCode/blob/master/.github/workflows/main.yml#L15.
> 
> I could use someone's help to fix this problem.

Working on Catalina 10.15.2 -> [Download](https://we.tl/t-s2VFMIBwzZ)

<img width="1024" alt="Captura de pantalla 2020-01-20 a las 17 14 49" src="https://user-images.githubusercontent.com/12648589/72741717-7fa0a380-3ba8-11ea-948c-fe75e889d20d.png">

Code of the master branch and compiled as @MichaelSeelisch suggested.

**Comment by antonreshetov** [comment]
It seems to be related to this - https://github.com/electron-userland/electron-builder/issues/4179

**Comment by blcarson** [comment]
Try opening the application normally once. After you cancel the error, right click and then hit "Open" - this should bypass Catalina's wonky "security"

**Comment by ibdf** [comment]
> Also having this problem. Was able to run the program by building it myself, as @MichaelSeelisch suggested.
> 
> This worked for me:
> 
> ```shell
> git clone https://github.com/antonreshetov/massCode
> cd massCode
> yarn install
> yarn build
> ```
> 
> For what it's worth, the `.app` that built for me is 2 MB larger than the official release, so they are not identical. Not sure how relevant this is.

I can confirm that building it myself worked. I am on Catalina 10.15.2.

**Comment by antonreshetov** [comment]
Please tell me, you run the application from the unpacked folder `./build/mac`?

**Comment by ibdf** [comment]
> Please tell me, you run the application from the unpacked folder `./build/mac`?

Correct. After yarn build is done, I copied the app from the build folder and moved it to the Applications folder. It opened right away.

**Comment by antonreshetov** [comment]
In the next CI build I will try to set the `dmg` target. From what I've read, there may be a problem with `zip`.

**Comment by antonreshetov** [comment]
Please check latest release with `dmg` - https://github.com/antonreshetov/massCode/releases/tag/v1.0.0-alpha.3

**Comment by ibdf** [comment]
> Please check latest release with `dmg` - https://github.com/antonreshetov/massCode/releases/tag/v1.0.0-alpha.3

Just tried. Same issue.

<img width="1048" alt="Screen Shot 2020-01-23 at 4 47 46 PM" src="https://user-images.githubusercontent.com/31483572/73026845-35b1fa80-3e00-11ea-9e04-4da4a3c9bee6.png">

**Comment by antonreshetov** [comment]
😭

**Comment by antonreshetov** [comment]
@ibdf I just installed macOS Catalina on Parralles, downloaded the dmg file and run the application. And it works. 🤷‍♂️
![2020-01-24_17-16-17](https://user-images.githubusercontent.com/17480987/73075699-8c393a80-3ecd-11ea-8f31-2a61fa98b3ad.png)

**Comment by ibdf** [comment]
Yeah, maybe the issue is not the OS version because @hreyeslo didn't seem to have this issue either. I'm still having it, but I am ok with the build it yourself solution for now.

**Comment by antonreshetov** [comment]
Are there any other questions or can I consider that this issue can be closed?

**Comment by ibdf** [comment]
I tested it again by downloading the dmg, and actually worked this time. So it's all good here.

**Comment by antonreshetov** [comment]
Glad to hear it!
P.S. please do not use the version below 1.0.0-alpha.4

**Comment by keirwilliams** [comment]
@antonreshetov The issue is the ZIP download. The DMG works fine but the ZIP is the one that causes "The application "massCode.app" can't be opened".
