### ISSUE TITLE
php code dont highlight without tag <?php ?> 

### ISSUE THREAD

**Issue by paultejedaf** [antonreshetov/massCode#23]
PHP snippet don't highlight code without php tags (<?php ?>)

![image](https://user-images.githubusercontent.com/5687572/72751104-67775700-3b9d-11ea-8620-1144891b668a.png)

**Comment by antonreshetov** [comment]
This is default behavior Monaco - https://microsoft.github.io/monaco-editor. Select PHP to see.
I am far from PHP, but I think the <?php > tag is important to the interpreter.

**Comment by antonreshetov** [comment]
@paultejedaf Are there any other questions or can I count that this issue can be closed?
