### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by fayazara** [antonreshetov/massCode#25]
## Describe the bug

Syntax highlighting does not work as described in the screenshot in masscode homepage. Tested with javascript, html & vue files.

## To Reproduce

- Open Masscode
- Create a new snippet
- Add some code 

## Expected behavior

Code should be highlighted

## Screenshots

![image](https://user-images.githubusercontent.com/15716057/72798041-31eb7000-3c68-11ea-8bc2-59a5be1498c2.png)

## Environment

Version: 1.41.1
OS version and name: Ubuntu 18.04

**Comment by antonreshetov** [comment]
Do you set the language at bottom left menu?

**Comment by fayazara** [comment]
Missed this. It's hardly visible, we could change this or hightlight the bottom row. 
Will raise a PR and add it myself

**Comment by antonreshetov** [comment]
I think the design will remain the same. But I will think about an improvement.

**Comment by laoshaw** [comment]
Can syntax highlight be turned on automatically based on filename? e.g. if it's a snippet.py then python syntax will be chosen, similar to hello.c for c,etc.
otherwise for each snippet I have to move the lower-left and pick a filetype from a very long list.
