### ISSUE TITLE
The theme preference is not being saved

### ISSUE THREAD

**Issue by alexandruspataru** [antonreshetov/massCode#26]
## Describe the bug

I'm not a huge fan of dark themes so I've tried to change the theme to **Light**, which does the thing. But when I restart the application, the theme is again set to **Dark**.

## To Reproduce

Set the Theme  to Light and restart the application.

## Environment

Version: 1.0.0-alpha
OS version and name: Windows 10

**Comment by alexandruspataru** [comment]
Not opening another issue, I'll just comment here: it would be nice if we could have the application to minimize to tray. This way we could keep it open all the time while not filling our taskbar.

**Comment by antonreshetov** [comment]
> Not opening another issue, I'll just comment here: it would be nice if we could have the application to minimize to tray. This way we could keep it open all the time while not filling our taskbar.

That's a good suggestion, thank you. I'll work on it.

**Comment by antonreshetov** [comment]
Please check, it should work in the version - https://github.com/antonreshetov/massCode/releases/tag/v1.0.0-alpha.1

**Comment by antonreshetov** [comment]
Closed because it was fixed
