### ISSUE TITLE
massCode cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by hos4m** [antonreshetov/massCode#27]
## Describe the bug

Getting this error window when I try to open the app for the first time

![image](https://user-images.githubusercontent.com/4350401/72901375-a6b9bb00-3cf7-11ea-81b2-05f869cf0237.png)

## To Reproduce
- Drag the app to the Application folder
- Open the app for the first time

## Expected behavior
The app should open normally

## Environment

Version: 1.0.0 alpha 1
OS version and name: macOS Catalina 10.15.2

**Comment by antonreshetov** [comment]
Yep, this is the default macOS protection behavior. You can turn it off. Unfortunately, the application does not have a signature at the moment.
