### ISSUE TITLE
Text/Code Wrapping Option

### ISSUE THREAD

**Issue by menjilx** [antonreshetov/massCode#28]
Hi,

I tried to locate the "wrapping option but I couldn't find it. Any plan on adding this feature?

Thank you

**Comment by antonreshetov** [comment]
Hi, just yesterday I added this feature, in the next release, today/tomorrow this option will be added.

**Comment by menjilx** [comment]
> Hi, just yesterday I added this feature, in the next release, today/tomorrow this option will be added.

awesome! Thank you for this useful tool! :) updated on product hunt already and will include this on my "Dev Tech Tools" review.

**Comment by antonreshetov** [comment]
Thank you very much! 🙂

**Comment by menjilx** [comment]
> Thank you very much! 🙂

:) your welcome man!
