### ISSUE TITLE
Can this be self hosted?

### ISSUE THREAD

**Issue by gerroon** [antonreshetov/massCode#3]
Is it possible to host this on a server?

**Comment by antonreshetov** [comment]
@gerroon No, application is planned to be standalone only.

**Comment by liangjingkanji** [comment]
iCloud?

**Comment by antonreshetov** [comment]
@liangjingkanji To use sync services like iCloud Drive, Google Drive of Dropbox, simply move storage to the corresponding synced folders in settings

**Comment by antonreshetov** [comment]
Are there any other questions or can I consider that this issue can be closed?
