### ISSUE TITLE
Menubar icon not visible in dark mode

### ISSUE THREAD

**Issue by blcarson** [antonreshetov/massCode#33]
## Describe the bug

Menubar icon is not visible when MacOS dark mode is enabled

## To Reproduce

Enable dark mode in MacOS

## Expected behavior

Icon should be white in dark mode and black in light mode

## Screenshots

![image](https://i.imgur.com/8bqUS7c.png)

## Environment

Version: 1.0.0-alpha.3
OS version and name: MacOS 10.15.2

**Comment by blcarson** [comment]
Turns out it was a simple fix - see PR #34. All that needed to be done was renaming the tray icon to follow electron's [template image naming convention](https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image)

**Comment by antonreshetov** [comment]
@blcarson thanks for PR
There's a bug in the fact that the icon became gray, it should be black. It also becomes white when clicked, and the blue background doesn't appear as it usually does.
![Kapture 2020-01-24 at 8 49 25](https://user-images.githubusercontent.com/17480987/73047489-05616f00-3e87-11ea-979a-ecc3b68c992b.gif)

**Comment by antonreshetov** [comment]
Closed because it was released in https://github.com/antonreshetov/massCode/releases/tag/v1.0.0-alpha.7

**Comment by blcarson** [comment]
Good catch - thanks!
