### ISSUE TITLE
Run as web app

### ISSUE THREAD

**Issue by SuperSandro2000** [antonreshetov/massCode#36]
I am switching between many machines and would like to have this program as a web app. Is that easily possible? Do you have any plans for that?
Thanks in advance!

**Comment by LukeCarlThompson** [comment]
I was just thinking about how great the ability to have a central repository that several users can share. It is a related problem so I thought I'd post here.

Would it be possible to use cloud storage for the snippets somehow? Or perhaps even sync up with github gists?
That might solve both issues.

Great project by the way!

**Comment by LukeCarlThompson** [comment]
You can use a cloud storage service as the db location. So should be able to share code between computers that way.

"You can use any service that provides cloud synchronization, such as iCloud Drive, Google Drive, Dropbox or other similar."

**Comment by SuperSandro2000** [comment]
Then I would still need to download massCode on every machine. I kinda want avoid that.

**Comment by antonreshetov** [comment]
At the moment there are no plans to make a web version
