### ISSUE TITLE
a way to sync snippets between machines

### ISSUE THREAD

**Issue by amitos80** [antonreshetov/massCode#4]
would be great if cloud support is in the plan, or other way to sync snnipets accross machines.
p.m
im also a web developer if you need another contributor for that feature lmn, would love to help with this

**Comment by arangates** [comment]
Currently I’m using snippets in chrome developer tools. I use a plugin to extract them to files and then create git repo out of it.

It would be great if this application could sync it to gists or guy repo

**Comment by antonreshetov** [comment]
@amitos80 
Of course there will be. You will be able to select a folder (iCloud, Dropbox, etc.) where the db of an application will be stored and synchronized between applications.

**Comment by antonreshetov** [comment]
Closed because it was implement in v0.2.0
