### ISSUE TITLE
`brew cask install masscode` would be sweet :)

### ISSUE THREAD

**Issue by hrdlnk** [antonreshetov/massCode#46]
`brew cask install masscode` would be sweet :)

**Comment by RedcoatAsher** [comment]
Not exactly a cask but you can `tap` any github repo... for example:

```
brew tap antonreshetov/massCode https://github.com/antonreshetov/massCode
```

**Comment by jiri** [comment]
I took the liberty of doing this, the PR is open [here](https://github.com/Homebrew/homebrew-cask/pull/78774) 😄

**Comment by karbassi** [comment]
@hrdlnk @antonreshetov You can close this issue as it's been fixed by @jiri! 🔥 

Thanks @jiri

**Comment by antonreshetov** [comment]
Closed because it was added in https://github.com/Homebrew/homebrew-cask/pull/78774
