### ISSUE TITLE
Quicker access to assistance's suggestions

### ISSUE THREAD

**Issue by bkielbasa** [antonreshetov/massCode#47]
## Describe the bug

While using the assistant, it would be awesome to be able to select the option without using the mouse. I can suggest just `enter` to choose the option I want.

**Comment by antonreshetov** [comment]
Closed because it was added in https://github.com/antonreshetov/massCode/pull/52

**Comment by bkielbasa** [comment]
is it released?

**Comment by antonreshetov** [comment]
@bkielbasa Yes, see - https://github.com/antonreshetov/massCode/releases/tag/v1.0.0
