### ISSUE TITLE
dos fragmentos  

### ISSUE THREAD

**Issue by dario1091** [antonreshetov/massCode#48]
## Describe the bug
Cuando hay dos fragmentos y el lenguaje es sql 
solo reconoce un fragmento como sql el otro fragmento queda como texto normal

## To Reproduce

Create snippet 
 create fragment1 
 writte code sql 
create fragment2
writte code sql

## Expected behavior
Se espera que los dos fragmentos reconozcan el lenguaje en el que esta escrito

## Screenshots
 
![IMG_20190907_184323](https://user-images.githubusercontent.com/11863861/73953621-abbd6380-48ce-11ea-9622-db3f6f691d03.jpg)
![no_reconoce](https://user-images.githubusercontent.com/11863861/73953622-ac55fa00-48ce-11ea-8025-971d526520b0.jpg)

**Comment by antonreshetov** [comment]
English please
