### ISSUE TITLE
when you press and hold any key or if you type quickly 

### ISSUE THREAD

**Issue by JohanJimenex** [antonreshetov/massCode#66]
## Describe the bug
when you press and hold any key or if you type quickly the cursor is positioned on the first line

## To Reproduce
when you press and hold any key or if you type quickly the cursor is positioned on the first line

**Comment by jrschumacher** [comment]
I'm not able to reproduce with version 1.0.2. When I press and hold it behaves like a Mac Catalyst app as you can see when holding the "a" key.

https://www.loom.com/share/ae07be5f11e24e49ab1e0e4e70af2a05

**Comment by estarq** [comment]
I've been using massCode for several days and it seems like there is no fixed typing speed at which it occurs. Sometimes it happens even if you type just several characters. If you press and hold any key it will not just change cursor position to the beginning of a document but also kind of move characters back and forth.

It's happening only within code editor and it doesn't matter which syntax you choose.

This is how it looks like:
1st line - tried to write _asd_, cursor changed it's position after 2 characters
3rd line - slow enough, no problems
5th line - fast typing
7th line - holding dot

![masscode](https://user-images.githubusercontent.com/61628924/77346775-af962f80-6d2e-11ea-81c0-f3f6a342cf25.gif)

```
Version: 1.1.0
Electron: 7.1.6
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279-23-electron.0
OS: Linux x64 5.3.0-42-generic
```

**Comment by jrschumacher** [comment]
@estarq what are your Keyboard settings. If I keep these settings it works fine. If I turn off all the flags then it acts as you show.

![image](https://user-images.githubusercontent.com/46549/77449602-5d492300-6daf-11ea-83f2-e6ca9cc7c484.png)

**Comment by estarq** [comment]
```
whoami@hostname ~> setxkbmap -print -verbose 10
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     pl
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+pl+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+pl+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

**Comment by alexrollin** [comment]
This happens for me on win10 also. It happened 6 times int he first 2 minutes I am using it and so here I am on github;

If I try typing anything in the snippet area it moves the cursor back up to the beginning of the snippet.

**Comment by oedmarap** [comment]
I have the same issue on Windows 10:

- Typing really quickly makes the cursor move to the beginning of the entire document
- Holding down a single key will replicate the same cursor jump

Additionally what I've discovered is that when this happens, _all ability to undo changes are lost_. I've included a screen GIF below to illustrate:

![masscode-undo-lost](https://user-images.githubusercontent.com/27732920/79133309-cd791200-7d79-11ea-991b-7614fde7c52f.gif)

In the above capture, I was able to use <kbd>CTRL</kbd> + <kbd>Z</kbd> in the first two instances to undo the changes made to `<html lang="en">`. The <kbd>Backspace</kbd> key was pressed individually for each character.

The third time however, the <kbd>Backspace</kbd> key was held down to remove the longer string of characters. After the cursor jumped to the beginning of the document <kbd>CTRL</kbd> + <kbd>Z</kbd> had no effect, and I was unable to recover the deleted characters.

```
Version: 1.2.0
Electron: 7.1.6
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by antonreshetov** [comment]
Please check latest release - https://github.com/antonreshetov/massCode/releases/tag/v1.2.1

**Comment by flenwan** [comment]
This is happening to me in 1.3.0
Windows 10
