### ISSUE TITLE
[feature] windows 10 support 

### ISSUE THREAD

**Issue by davidbernegger** [antonreshetov/massCode#7]
Just for acknowledging that some might want to use this for their win machines.

**Comment by ipokkel** [comment]
2nd that

**Comment by davidbernegger** [comment]
According to his latest commit, there seem plans to support all the os's: https://github.com/antonreshetov/massCode/commit/833f3a0c20582ab82efda2a7dba61a34808f7cf5

**Comment by antonreshetov** [comment]
Hey take a look - https://github.com/antonreshetov/massCode/releases/tag/v0.3.3
There's still a lot ahead of catching the bugs, but there's already something... 😀
