### ISSUE TITLE
Pixelated Icon

### ISSUE THREAD

**Issue by sawden** [antonreshetov/massCode#70]
## Describe the bug

The Icon for Windows is Pixelated.

## Screenshots
![S](https://user-images.githubusercontent.com/36924392/75779916-d3cba580-5d5a-11ea-9862-41659046ba3c.PNG)

## Environment

Version:
OS version and name: Windows 10
Screen resolution: 1280x1024

**Comment by antonreshetov** [comment]
I know about this bug, but I can't figure out what the reason is. If there's anybody who wants to help, that was cool.

**Comment by vadimkozhin** [comment]
Hey! I've fixed the icon.

You can [download](https://drive.google.com/open?id=1sB4f4MzTImYo5uGQ0KOozq0LB6mrLSFG) it.

**Comment by antonreshetov** [comment]
Closed because it was fixed in latest release - https://github.com/antonreshetov/massCode/releases/tag/v1.2.0
