### ISSUE TITLE
backup now button doesn't work

### ISSUE THREAD

**Issue by dcy10000** [antonreshetov/massCode#72]
## Describe the bug

when I click the "backup now" button, nothing happened.
Is this backup function stable now?

**Comment by antonreshetov** [comment]
I couldn't reproduce this bug.

**Comment by estarq** [comment]
On Linux default directory for massCode's backups is ~/massCode/backups which simply doesn't exist.
When it does, everything seems to work just fine.

**Comment by dcy10000** [comment]
> On Linux default directory for massCode's backups is ~/massCode/backups which simply doesn't exist.
> When it does, everything seems to work just fine.

thx. It works! 
But, the introduction I see is that "Backup will be created automatically when massCode is running.",
I haven't seen any automatic backups yet. 
How often does it trigger ？

**Comment by estarq** [comment]
Take a look:
https://github.com/antonreshetov/massCode/blob/4a7bc7c6793d0f599741c80185ac52176bd21e89/src/renderer/datastore.js#L98-L120

**Comment by antonreshetov** [comment]
Closed because it was fixed in #90
