### ISSUE TITLE
Can't change backup directory

### ISSUE THREAD

**Issue by estarq** [antonreshetov/massCode#83]
## Describe the bug

When trying to change directory using "Change folder" button, the indicated directory is not chosen even though it's path is visible next to the button.
Clicking "Backup now" button results in:
`Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '/home/username/massCode/backups'             (renderer.js:2)`
as the default backup directory doesn't exist (#72).

After relaunching massCode, the default path (instead of the previously chosen one) is once again visible next to the "Backup now" button.

## To Reproduce

1. Go to the Preferences
2. Choose another folder for storing backups
3. Press "Backup now" to see that it doesn't create a backup
4. Relaunch and go to the Preferences

## Expected behaviour

Changing backup directory after choosing it with "Change folder" button.

## Environment

```
Version: 1.1.0
Electron: 7.1.6
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279-23-electron.0
OS: Linux x64 5.3.0-42-generic
```

**Comment by antonreshetov** [comment]
Closed because it was fixed in #90
