### ISSUE TITLE
After upgrade - black window

### ISSUE THREAD

**Issue by bkielbasa** [antonreshetov/massCode#88]
## Describe the bug

After upgrading to the newest version, the app stopped working.

## To Reproduce

Not sure :) 

## Screenshots

![image](https://user-images.githubusercontent.com/1235620/77998581-9a725f80-7331-11ea-8b60-3ca7af560a6d.png)

![image](https://user-images.githubusercontent.com/1235620/77998619-a3fbc780-7331-11ea-9e84-72e6b4b03723.png)

## Environment

![image](https://user-images.githubusercontent.com/1235620/77998653-b413a700-7331-11ea-91b7-2ca1ec4ff374.png)

**Comment by ktalley-vtech** [comment]
I have experienced something similar on macOS (10.15.4), but not consistently.  If massCode app stays minimized for a period of time, and then I click it (to restore window), I get the black screen as shown in original screenshot.  I have to exit/quit massCode and restart to see the expected screen contents again.  Tray icon, however, still seems to function normally (even if the app screen displays blank/black screen) -- at least that is my personal experience.

**Comment by bkielbasa** [comment]
unexpectedly, it works now. I did nothing :)

**Comment by antonreshetov** [comment]
Closed because it was fixed in #90
