### ISSUE TITLE
FEATURE: Cloud integration

### ISSUE THREAD

**Issue by VladimirMikulic** [antonreshetov/massCode#91]
Hi! First of all, I would like to thank you for creating this application.
It's definitely the best snippet manager that I've used, but there is one option that I would like to have.

Would it be possible to synchronize the snippets with the cloud Google Drive, Dropbox...
This is especially required for Linux because all major cloud providers don't have a synchronization app that are available for Linux.

Thank you.

**Comment by antonreshetov** [comment]
@VladimirMikulic To use sync services like iCloud Drive, Google Drive of Dropbox, simply move storage to the corresponding synced folders. Preferences -> Storage.

**Comment by VladimirMikulic** [comment]
@antonreshetov That's kind of a problem. For example, Google Drive doesn't have a sync client for Linux :(

**Comment by antonreshetov** [comment]
You can probably use - https://github.com/vitalif/grive2.

**Comment by VladimirMikulic** [comment]
@antonreshetov thank you very much on this resource. I'll make sure to check it out!

**Comment by VladimirMikulic** [comment]
@antonreshetov alright, this solved the problem.
I have one more feature request if you don't mind.
Would it be possible to choose the syntax highlighting theme or even allow users to create their own?
Since the main engine is Microsoft's Monaco editor, it shouldn't be too hard to implement?

I am willing to assist you.

**Comment by antonreshetov** [comment]
I think two themes are enough.
