### ISSUE TITLE
Support Dart/Flutter language

### ISSUE THREAD

**Issue by zaprogrammer** [antonreshetov/massCode#97]
## Describe the bug

As a Dart/Flutter developer, I can't find those languages in the language menu.

## To Reproduce

**Example:**

- Select the language dropdown menu in the bottom of the editor
- Scroll down to find dart or flutter languages
- Not found!

## Expected behavior

Expected to find those languages as options in this dropdown.
## Screenshots
![image](https://user-images.githubusercontent.com/1791059/79938106-f8d7bd00-845b-11ea-8cbb-b28f181a99ec.png)

## Environment

Version: [e.g. 1.2.1]
OS Catalina 10.15.4

**Comment by antonreshetov** [comment]
@zaprogrammer It’s not the bag. Monaco editor Editor does not support Dart language by default.

**Comment by Clusiv** [comment]
any progress?
Do i need to compile masscode with this commit or what?

**Comment by antonreshetov** [comment]
Closed because it was added in #107
